from enum import Enum


class ButtonNames(Enum):
    ACCOUNT_MANAGER = "button_account_manager"
    ADD_NEW_ACCOUNT = "button_add_new_account"
    APP_CONFIGURATIONS = "button_app_configurations"
    AUTOMATIC_QUEUE_ACCEPT = "button_automatic_queue_accept"
    COLLECT_DATA_ON_STARTUP = "button_collect_data_on_startup"
    COLLECT_ACCOUNT_DATA = "button_collect_account_data"
    CHAMPIONS = "button_champions"
    DELETE = "button_delete"
    EDIT = "button_edit"
    INFO = "button_info"
    LOGIN = "button_login"
    OPGG = "button_opgg"
    SELECT_ACCOUNT = "button_select_account"
    SKINS_CHAMPIONS = "button_skins_champions"
    SKINS = "button_skins"
    SUBMIT_NEW_ACCOUNT = "button_submit_new_account"
    SUBMIT_EDITED_ACCOUNT = "button_submit_edited_account"
    REMOVE_ACCOUNT_FILTER = "button_remove_account_filter"

class LabelNames(Enum):
    APPLICATION_LOGO = "label_application_logo"
    ACCOUNT_ID = "label_account_id"
    COLLECTING_DATA = "label_collecting_data"
    COPY_SUMMONER_NAME = "label_copy_summoner_name"
    COPY_TAGLINE = "label_copy_tagline"
    COPY_USERNAME = "label_copy_username"
    COPY_PASSWORD = "label_copy_password"
    ADD_EDIT_SUMMONER_NAME = "label_add_edit_summoner_name"
    ADD_EDIT_TAGLINE = "label_add_edit_tagline"
    ADD_EDIT_USERNAME = "label_add_edit_username"
    INFO_SUMMONER_NAME = "label_info_summoner_name"
    INFO_TAGLINE = "label_info_tagline"
    INFO_USERNAME = "label_info_username"
    NAME = "label_name"
    RANK = "label_rank"
    HEADER_REGION = "label_header_region"
    GAMES_PLAYED = "label_games_played"
    WINRATE = "label_winrate"
    REGION = "label_region"
    UNDER_DEVELOPMENT = "label_under_development"
    ACTUAL_ACCOUNT_ID = "label_actual_account_id"
    ACTUAL_NAME = "label_actual_name"
    ACTUAL_RANK = "label_actual_rank"
    ACTUAL_REGION = "label_actual_region"
    ACTUAL_GAMES_PLAYED = "label_actual_games_played"
    ACTUAL_WINRATE = "label_actual_winrate"

class LineEditNames(Enum):
    ADD_ACCOUNT_SUMMONER_NAME = "line_edit_add_account_summoner_name"
    ADD_ACCOUNT_TAGLINE = "line_edit_add_account_tagline"
    ADD_ACCOUNT_USERNAME = "line_edit_add_account_username"
    ADD_ACCOUNT_PASSWORD = "line_edit_add_account_password"
    EDIT_ACCOUNT_SUMMONER_NAME = "line_edit_edit_account_summoner_name"
    EDIT_ACCOUNT_TAGLINE = "line_edit_edit_account_tagline"
    EDIT_ACCOUNT_USERNAME = "line_edit_edit_account_username"
    EDIT_ACCOUNT_PASSWORD = "line_edit_edit_account_password"
    INFO_SUMMONER_NAME = "line_edit_info_summoner_name"
    INFO_TAGLINE = "line_edit_info_tagline"
    INFO_USERNAME = "line_edit_info_username"
    INFO_PASSWORD = "line_edit_info_password"
    CHAMPIONS_SEARCH = "line_edit_champions_search"    

class ComboBoxNames(Enum):
    ADD_ACCOUNT_REGION = "combo_box_add_account_region"
    EDIT_ACCOUNT_REGION = "combo_box_edit_account_region"

class CheckBoxNames(Enum):
    ADD_ACCOUNT_PASSWORD = "check_box_add_account_password"
    EDIT_ACCOUNT_PASSWORD = "check_box_edi_account_password"
    INFO_ACCOUNT_PASSWORD = "check_box_info_account_password"